# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx
#   labels:
#     app: nginx
# spec:
#   type: NodePort
#   ports:
#     - port: 80
#       targetPort: 80
#       protocol: TCP
#       name: http
#   selector:
#     app: nginx
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nodejs
#   labels:
#     app: nodejs
# spec:
#   type: NodePort
#   ports:
#     - port: 6666
#       targetPort: 6666
#       protocol: TCP
#       name: http2
#   selector:
#     app: nodejs
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eyeballr-beta-nodejs-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nodejs
        tier: backend
    spec:
      containers:
        - name: nodejs
          image: gcr.io/eyeballr-beta/nodejs:14e1557
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6666
              hostPort: 6666
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ok
              port: 6666
            initialDelaySeconds: 15
            timeoutSeconds: 1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eyeballr-beta-nginx-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: gcr.io/eyeballr-beta/nginx:14e1557
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
              name: webfe
          livenessProbe:
            httpGet:
              path: /ok.html
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 1
